# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1Rpiflg8HejJd7Uoxo_Rh0sn8jyL0fd
"""

pip install streamlit

import streamlit as st
import joblib
import numpy as np

# Memuat model
model = joblib.load('glucovision_model.sav')

# Judul aplikasi
st.title('Aplikasi Prediksi Diabetes')

# Input dari pengguna
pregnancies = st.number_input('Jumlah Kehamilan', min_value=0)
glucose = st.number_input('Tingkat Glukosa', min_value=0)
blood_pressure = st.number_input('Tekanan Darah', min_value=0)
skin_thickness = st.number_input('Ketebalan Kulit', min_value=0)
insulin = st.number_input('Tingkat Insulin', min_value=0)
bmi = st.number_input('Indeks Massa Tubuh (BMI)', min_value=0.0)
diabetes_pedigree_function = st.number_input('Fungsi Pedigri Diabetes', min_value=0.0)
age = st.number_input('Usia', min_value=0)

# Tombol untuk melakukan prediksi
if st.button('Prediksi'):
    # Mengumpulkan data input ke dalam array
    input_data = np.array([[pregnancies, glucose, blood_pressure, skin_thickness, insulin, bmi, diabetes_pedigree_function, age]])

    # Lakukan prediksi
    prediction = model.predict(input_data)

    # Menampilkan hasil prediksi
    if prediction[0] == 1:
        st.write('Hasil Prediksi: **Diabetes Positif**')
    else:
        st.write('Hasil Prediksi: **Diabetes Negatif**')